version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: nutrition-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Tuan@nh04
      MYSQL_DATABASE: nutrition_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nutrition-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nutrition-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/nutrition_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Tuan@nh04
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - nutrition-network

networks:
  nutrition-network:
    driver: bridge

volumes:
  mysql-data: